### ISSUE TITLE
Can't use the plugin

### ISSUE THREAD

**Issue by carl0shd** [pnthach95/flipper-plugin-react-native-mmkv-storage#1]
Hi @pnthach95, I can't use the plugin with Flipper, my stack is:

react-native-mmkv-storage version 0.8.0
react-native 0.69.4
flipper version 0.158.0

when I open Flipper I see the plugin unavailable:
<img width="233" alt="Screen Shot 2022-08-17 at 5 50 31 PM" src="https://user-images.githubusercontent.com/8359234/185257137-b92d5950-e6b2-4fbd-8c28-3348cca5ed6d.png">

**Comment by pnthach95** [comment]
You need to install [this](https://github.com/pnthach95/rn-mmkv-storage-flipper) in your React Native project. I updated [README](https://github.com/pnthach95/flipper-plugin-react-native-mmkv-storage/commit/f3dd1a2808a627d1e345a76697923341bd7ee8d0) about this.

**Comment by carl0shd** [comment]
Thanks 👍
