### ISSUE TITLE
Cannot edit record

### ISSUE THREAD

**Issue by gomikestrat** [pnthach95/flipper-plugin-react-native-mmkv-storage#2]
Flipper 0.166.0
react-native: 0.69.5
react-native-mmkv-storage: 0.8.0
flipper-plugin-react-native-mmkv-storage: 1.1.0

When selecting a record nothing appears on the sidebar, therefore the record cannot be edited.

![image](https://user-images.githubusercontent.com/15107010/195302989-510cb33d-77f2-45f0-b697-949f0a2d548b.png)

**Comment by pnthach95** [comment]
After upgrade flipper, I can't edit either. I don't know why. Downgrade flipper to the version I made plugin don't help.

**Comment by pnthach95** [comment]
I just remembered when I fixed [duplicate key bug](https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/276), I forgot to update new key that leads to this bug. Please update plugin to v1.2.0.
