### ISSUE TITLE
objects are hard to read

### ISSUE THREAD

**Issue by pvinis** [pnthach95/flipper-plugin-react-native-mmkv-storage#3]
<img width="550" alt="Screenshot 2023-01-30 at 16 44 01" src="https://user-images.githubusercontent.com/100233/215539994-81832470-22a5-4dea-998b-2ae08b992b6d.png">
it would be great to show these in a better way, and not just as a string

**Comment by pnthach95** [comment]
I can't change format inside data table, so I add formatting options in right panel, like Network plug-in. Available in v1.3.1. Please update it in Flipper.
